# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radius.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        Form.setStyleSheet("background-color:rgb(158, 151, 255);")
        self.create = QtWidgets.QPushButton(Form)
        self.create.setGeometry(QtCore.QRect(220, 400, 151, 23))
        self.create.setStyleSheet("border-radius:5px;\n"
"background-color:rgb(255, 124, 177);")
        self.create.setObjectName("create")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.create.setText(_translate("Form", "Создать окружность"))
